#!/bin/sh

# = Functions =

# Purpose: Emergency local rescue shell.
# TODO: Must this be a function?
do_shell() {
   echo "Do your best!"
   /bin/busybox --install -s
   exec /bin/sh
}

# = Main Procedure =

# Get ready to get the system ready.
/bin/mount -t devtmpfs none /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

# Remember some things...
_CFG_U="`/sbin/cryptscript -u`"

# Try to mount the unencrypted boot for cryptscript.
CFG_U_FOUND=0
for BLK_PROBE_ITER in `ls -1 /dev/sd*`; do
   /bin/mount -o ro "$BLK_PROBE_ITER" /mnt/boot 2>/dev/null
   if [ -f "$_CFG_U" ]; then
      CFG_U_FOUND=1
      echo "Found unencrypted config file."
      break
   fi
done

if [ -f "$_CFG_U" ] && [ -n "`/bin/grep "^SSH" "${_CFG_U}"`" ]; then
   # Start the remote listener.
   # TODO
   echo "Started remote decryption service."
fi

# Get the user password.
/sbin/cryptscript

if [ 0 != $? ]; then
   # Failure to mount!
   #/sbin/reboot
   do_shell
fi

/sbin/splash_util --mmode=s -c setmode

# Clean up and prepare for the real thing.
/bin/umount /mnt/boot 2>/dev/null
/bin/umount /dev
/bin/umount /proc
/bin/umount /sys

exec switch_root /mnt/root /sbin/init

