#!/bin/sh

/sbin/cryptscript

if [ 0 != $? ]; then
   # Failure to mount!
   #/sbin/sysmounts -u
   #/sbin/reboot -f
   exit
else
   # Clean up and prepare for the real thing.
   killall -USR1 init && \
   killall cryptscript
   exit
fi

#/sbin/splash_util --mode=s -c setmode
#/sbin/sysmounts -u

#exec switch_root /mnt/root /sbin/init

